import React from "react";
import { signOut, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Head from "next/head";
const Dashboard = () => {
  const { data: sessionData, status } = useSession();
  const router = useRouter();

  React.useEffect(() => {
    if (status === "unauthenticated") {
      void router.push("/");
    }
  }, [sessionData, status, router]);

  if (status === "loading" || !sessionData) {
    return null;
  }

  return (
    <>
      <Head>
        <title>GitChecker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <button onClick={() => void signOut({ callbackUrl: "/" })} className="">
          Sign Out
        </button>
      </main>
    </>
  );
};

export default Dashboard;
